"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 10:21:18.593366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('host_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('agent_ip', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('first_seen', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('host_id')
    )
    op.create_index(op.f('ix_assets_agent_ip'), 'assets', ['agent_ip'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_state',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('last_attempt_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('watermark', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('events',
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('event_time', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('original_sensor', sa.String(length=32), nullable=False),
    sa.Column('collector_path', sa.JSON(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('agent_ip', sa.String(length=64), nullable=True),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('original_severity', sa.String(length=32), nullable=True),
    sa.Column('severity_system', sa.String(length=32), nullable=False),
    sa.Column('normalized_priority', sa.String(length=16), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('event_uid')
    )
    op.create_index(op.f('ix_events_event_time'), 'events', ['event_time'], unique=False)
    op.create_index(op.f('ix_events_host_id'), 'events', ['host_id'], unique=False)
    op.create_index(op.f('ix_events_normalized_priority'), 'events', ['normalized_priority'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index('ix_events_time_uid', 'events', ['event_time', 'event_uid'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opened_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('merged_into', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_host_id'), 'incidents', ['host_id'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('action_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_proposals_incident_id'), 'action_proposals', ['incident_id'], unique=False)
    op.create_table('external_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['event_uid'], ['events.event_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_refs_event_uid'), 'external_refs', ['event_uid'], unique=False)
    op.create_table('incident_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_audit_incident_id'), 'incident_audit', ['incident_id'], unique=False)
    op.create_table('incident_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_uid'], ['events.event_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_candidates_event_uid'), 'incident_candidates', ['event_uid'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('linked_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_uid'], ['events.event_uid'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uid')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incident_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_notes_incident_id'), 'incident_notes', ['incident_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('incident_version', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('recipient_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_try_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=256), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_notifications_incident_id'), 'notifications', ['incident_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('notification_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_attempts_notification_id'), 'notification_attempts', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_attempts_notification_id'), table_name='notification_attempts')
    op.drop_table('notification_attempts')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_incident_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_incident_notes_incident_id'), table_name='incident_notes')
    op.drop_table('incident_notes')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incident_candidates_event_uid'), table_name='incident_candidates')
    op.drop_table('incident_candidates')
    op.drop_index(op.f('ix_incident_audit_incident_id'), table_name='incident_audit')
    op.drop_table('incident_audit')
    op.drop_index(op.f('ix_external_refs_event_uid'), table_name='external_refs')
    op.drop_table('external_refs')
    op.drop_index(op.f('ix_action_proposals_incident_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_host_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_events_time_uid', table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_normalized_priority'), table_name='events')
    op.drop_index(op.f('ix_events_host_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_time'), table_name='events')
    op.drop_table('events')
    op.drop_table('connector_state')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_assets_agent_ip'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
