"""session_id confidence token_hash merge_requests

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 11:09:31.994109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decided_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_requests_source_id'), 'merge_requests', ['source_id'], unique=False)
    op.create_index(op.f('ix_merge_requests_status'), 'merge_requests', ['status'], unique=False)
    op.add_column('events', sa.Column('session_id', sa.String(length=128), nullable=True))
    op.add_column('incidents', sa.Column('confidence', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('token_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_token_hash'), 'users', ['token_hash'], unique=True)
    roles = sa.table('roles', sa.column('name', sa.String), sa.column('permissions', sa.JSON))
    # Frozen historical seed; later revisions add new permissions.
    PERMISSIONS = {
        "viewer": {"read"},
        "analyst": {"read", "investigate"},
        "operator": {"read", "investigate", "transition", "merge", "hunt", "approve"},
        "admin": {"read", "investigate", "transition", "merge", "hunt", "approve", "admin"},
    }
    op.bulk_insert(roles, [{'name': k, 'permissions': sorted(v)} for k, v in PERMISSIONS.items()])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM roles")
    op.drop_index(op.f('ix_users_token_hash'), table_name='users')
    op.drop_column('users', 'token_hash')
    op.drop_column('incidents', 'confidence')
    op.drop_column('events', 'session_id')
    op.drop_index(op.f('ix_merge_requests_status'), table_name='merge_requests')
    op.drop_index(op.f('ix_merge_requests_source_id'), table_name='merge_requests')
    op.drop_table('merge_requests')
    # ### end Alembic commands ###
